### PR TITLE
Make sure import paths are sorted before iteration

### PR DESCRIPTION
**Pull request by hferentschik**
fixes issue #82

### CODE REVIEW

**Review by petergtz — CHANGES_REQUESTED** [review]
Hi @hferentschik,

Thank you very much for your PR. Your changes make a lot of sense and I would like to merge them. Just one minor thing: would you mind moving the `sortedKeys` function into a separate `util` package and make it public there? I know util packages are somewhat controversial, but this function is very generic and is not specific to mockgen, so ideally it's in its own package. Also, that would avoid the need to move mockgen_test into mockgen. I think the util package could either live directly in the pegomock directory, or here in the mockgen directory. Choose whatever you think makes more sense. Thank you.

**Comment by hferentschik** [comment]
> Thank you very much for your PR. 

No problem.

> Your changes make a lot of sense and I would like to merge them. 

Awesome.

> Just one minor thing: would you mind moving the sortedKeys function into a separate util package and make it public there? I know util packages are somewhat controversial, but this function is very generic and is not specific to mockgen, so ideally it's in its own package.

Sure. In fact, I was initially looking at the existing _util_ package under _pegomock_, but then I was thinking that this _util_ package is probably the one which is used as a utility package for the usage of pekomock. So when you say move _sortedKey_ into a util package, do you mean a _util_ package under _mockgen_? 

> Also, that would avoid the need to move mockgen_test into mockgen. 

Sure. 

> I think the util package could either live directly in the pegomock directory, or here in the mockgen directory. Choose whatever you think makes more sense. Thank you.

:-) comes the answer. I think I prefer the latter. I will update the PR.

**Comment by hferentschik** [comment]
I pushed an update.

**Review by petergtz — APPROVED** [review]

**Comment by petergtz** [comment]
Thank you! Merged.

**Pull request merged**
