### PR TITLE
Add support for vendor packages

### PR DESCRIPTION
**Pull request by aakn**
Takes the vendor package import path as an argument.
Then remove the vendor package from the import path.

Example:
If I have my dependencies in vendor, and have an external dependency (example sqlx). I would import that as 
`sqlx "github.com/jmoiron/sqlx"`

But the generated mock would have the following import:
`sqlx "github.com/aakn/test/vendor/github.com/jmoiron/sqlx"`

This is handled by removing the vendor path from the import path. 

Usage:
Add an argument `--vendor_path=github.com/org/project/vendor` to the CLI

### CODE REVIEW

**Comment by petergtz** [comment]
Hi @aakn,

Thanks so much for your contribution. Proper handling of vendor directories is really missing in pegomock, and it's awesome to see that you've picked up this missing feature and sent a PR.

What do you think about making the vendor path configuration completely automatic? I.e. instead of passing it in as a CLI argument, let the code generator detect if something is a vendor path and remove it from the import path automatically. I think that detection would be possible, either by following [Go's documented rules](https://golang.org/cmd/go/#hdr-Vendor_Directories) on how vendor directories work, or by using some library functions from the Go standard library.

Then a user never has to think about it again.

Thanks,
Peter

**Comment by aakn** [comment]
I had earlier planned to do it automatically. But the only way I could think of that was to check if the import path contains 'vendor', and remove the vendor path prefix. 
I didn't opt for this approach because I am not sure if other developers need it. But yeah, if they have vendor packages in their working dir, then they do need it.

Does that sound correct? I'm not sure if I've missed any cases.

**Comment by petergtz** [comment]
> Does that sound correct? I'm not sure if I've missed any cases.

Yes, I think that does sound correct. I suggest to start with that.

> I didn't opt for this approach because I am not sure if other developers need it.

I think `vendor` is never allowed to be part of an import path. So it's probably safe to assume developers never need it in there.

Should we notice that this approach doesn't work in all cases, we can still tune it. Does that sound good to you?

**Comment by aakn** [comment]
Yup, this sounds good. I'll update the pr.

**Comment by petergtz** [comment]
Looks great! Thank you, @aakn.

**Comment by petergtz** [comment]
@aakn Do you happen to have a Twitter handle? I want to post about the update on Twitter and would like to mention you.

**Comment by lkysow** [comment]
Nice work @aakn :D Now I can remove these `go:generate` `sed` lines!

```
//go:generate pegomock generate --use-experimental-model-gen --package mocks -o mocks/mock_runner.go Runner
//go:generate sed -i "" -e "s#go_version \"github.com/hootsuite/atlantis/vendor/github.com/hashicorp/go-version\"#go_version \"github.com/hashicorp/go-version\"#" mocks/mock_runner.go
```

**Pull request merged**
